apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: login
  name: metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: login
