apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: login-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: login-role
subjects:
- kind: ServiceAccount
  name: login
  namespace: system
