apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: login
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ws-role
subjects:
- kind: ServiceAccount
  name: sa
  namespace: login
