apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - idp.do.storageos.net
    secretName: ingress-cert
  rules:
  - host: idp.do.storageos.net
    http:
      paths:
      - path: /login/
        pathType: Exact
        backend:
          service:
            name: login-web-service
            port:
              number: 443
